# Generated by Django 3.1.7 on 2021-02-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plants',
            options={},
        ),
    ]
