# Generated by Django 3.1.7 on 2021-02-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210224_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
