# Generated by Django 3.1.7 on 2021-02-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210225_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='aname',
            new_name='aName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='cname',
            new_name='cName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='ename',
            new_name='eName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='fname',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='gname',
            new_name='gName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='sname',
            new_name='sName',
        ),
    ]
